### PR TITLE
[DO NOT MERGE] v1.0.0

### PR DESCRIPTION
**Pull request by tyronjung-quizlet**
### Ticket
Link to ticket: **No linked ticket**

### What has been done
- Do not merge. Just opening to make sure that Travis passes.

### CODE REVIEW

**Comment by lexidor** [comment]
Yeah, this is correct.
Just a nit, you are saying that hhvm 4.26 is not compatible (implicitly 4.25 is), but the last tested version is 4.24.
I'll try to do a composer install on hhvm 3.30, 4.19 and 4.25 once this is published to packagist.
Can you give it a shot on 3.25?

**Comment by tyronjung-quizlet** [comment]
> Just a nit, you are saying that hhvm 4.26 is not compatible (implicitly 4.25 is), but the last tested version is 4.24.

Fair point.

> Can you give it a shot on 3.25?

Yes.

**Comment by tyronjung-quizlet** [comment]
Though actually, I feel like we excluded 4.25 for a reason...

**Comment by lexidor** [comment]
> Though actually, I feel like we excluded 4.25 for a reason...

I just tested on hhvm `4.($i*2)` and hhvm 4.1, because that is still following the old hhvm release schedule.

**Comment by tyronjung-quizlet** [comment]
Gotcha.

**Pull request closed without merging**
