### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by tyronjung-quizlet**

### CODE REVIEW

**Review by lexidor — APPROVED** [review]
:owl: approved

**Comment by tyronjung-quizlet** [comment]
😱was not expecting you to be around lol.

**Comment by lexidor** [comment]
> :screamwas: not expecting you to be around lol.

Timezones...

**Comment by lexidor** [comment]
The test suite takes about 16 minutes because it tests on a bajllion hhvm versions.
You could knock out every two out of three to speed it up. Keep the ones clustered around 4.26 alive.

**Comment by tyronjung-quizlet** [comment]
True... I'll do it in the next PR.

**Pull request merged**
